name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  UnitTest:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    - name: Available simulators
      run: xcrun simctl list --json devices available
    - name: Available sdks
      run: xcodebuild -showsdks
    - name: Build for iOS
      run: xcodebuild build-for-testing -scheme FastLane_Integration -project FastLane_Integration.xcodeproj -destination "platform=iOS Simulator,OS=14.0,name=Any iOS Device" | xcpretty && exit ${PIPESTATUS[0]}
    - name: Run iOS tests
      run: xcodebuild test-without-building -scheme FastLane_Integration -project FastLane_Integration.xcodeproj -destination "platform=iOS Simulator,OS=latest,name=Any iOS Device" | xcpretty && exit ${PIPESTATUS[0]}


