name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  UnitTest:
    runs-on: macOS-11
    steps:
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run:  sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer
    - name: Available simulators
      run: xcrun simctl list --json     
    - name: Available sdks
      run: xcodebuild -showsdks
    - name: Run unit tests
      run: xcodebuild test -scheme FastLane_Integration -project FastLane_Integration.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0' | xcpretty && exit ${PIPESTATUS[0]}

